### ISSUE TITLE
Inference results seems weird using default trained model

### ISSUE THREAD

**Issue by hotdog132** [weichen582/RetinexNet#1]
I tried to follow the steps to generate enhanced images, but the results seems weird. Is that normal?

Inference results: https://drive.google.com/drive/folders/1TlEPm40HJS-A7qwD5ikY6DfEleG19d0T?usp=sharing

**Comment by kk60258** [comment]
Get the same results as @hotdog132 provided

**Comment by weichen582** [comment]
Sorry for the late reply. The results in this link are indeed the results enhanced by our method. That is normal.

We are aware that our method is just the first step to combine the Retinex decomposition with CNN. Looking forward to more powerful methods!

**Comment by lccui** [comment]
The images in the test_results can not open.BMP has bogus header data.How to fix it?
